### ISSUE TITLE
Allow `lrange` to take ints

### ISSUE THREAD

**Issue by jwoertink** [jgaskins/redis#16]
The `lrange` method requires all strings to be passed, so you have this:

```crystal
redis.lrange(key, "0", "-1")
```

https://github.com/jgaskins/redis/blob/386dc498085527c04b43e6eff5e1751e995d1b80/src/commands/list.cr#L38

but it looks like `zrange` does allow for ints

```crystal
redis.zrange(key, 0, -1)
```

https://github.com/jgaskins/redis/blob/386dc498085527c04b43e6eff5e1751e995d1b80/src/commands/sorted_set.cr#L15

**Comment by jgaskins** [comment]
Yep, the API originally prescribed using strings for all args for 2 reasons:

- the Redis server expects to receive an array of strings
- providing a string literal would not involve a heap allocation, but a numeric literal that is then stringified does
  - a big reason to choose this shard over the other popular one is that this one is highly tuned to avoid heap allocations whenever feasible
  - for example, this shard prefers to use tuples for Redis commands instead of arrays, but when that isn't feasible we [right-size the array from the beginning](https://github.com/jgaskins/redis/blob/302fc59049a08767efcb04816bb7a6b854fdeaf9/src/commands.cr#L225) instead of [allocating a small array](https://github.com/stefanwille/crystal-redis/blob/fa7121fb3acc4b9ffb951ecb716f767f59b4ce8d/src/redis/commands.cr#L246) and having to realloc the buffer as it grows.

But then, I wanted to accept timestamps for `zrange`, which then required converting to strings through an int, so as you mentioned, I added support for ints there. Ultimately, I feel like we should probably support the quick and easy thing even if that way is a little less performant, but remain optimized internally. At the edges of the API the performance difference probably doesn't matter anywhere near as much.

**Comment by jgaskins** [comment]
Wait, I was thinking of `xrange` requiring timestamps for streams. I don't even remember adding `zrange`. I must've had a reason for it, though. 😂
