### ISSUE TITLE
can't use this shard together with crystal-mysql

### ISSUE THREAD

**Issue by Manu-sh** [jgaskins/redis#3]
can't using this shard with `crystal-mysql`, while `stefanwille/crystal-redis` is not affect by this issue
```
Resolving dependencies
Fetching https://github.com/jgaskins/redis.git
Fetching https://github.com/jgaskins/crystal-db.git
Fetching https://github.com/crystal-lang/crystal-mysql.git
Error shard name (db) has ambiguous sources: 'git: https://github.com/jgaskins/crystal-db.git' and 'git: https://github.com/crystal-lang/crystal-db.git'.
```

**Comment by jgaskins** [comment]
This shard currently depends on my fork of `crystal-db` that allows its `DB::Pool` class to be used as a general-purpose connection pool since it's threadsafe. `stefanwille/crystal-redis` uses the `ysbaddaden/pool` shard which is not (I found this out the hard way running an app with `-Dpreview_mt`). More context on that [here](https://github.com/crystal-lang/crystal-db/issues/122).

I submitted the branch this shard uses as [a PR to `crystal-db`](https://github.com/crystal-lang/crystal-db/pull/131) to allow `DB::Pool` to be used as a general-purpose connection pool and it just got merged a few days ago, so I should be able to update this shard to match that.

**Comment by jgaskins** [comment]
It's okay, you don't need to close this, it's definitely a problem. 🙂

**Comment by z64** [comment]
@Manu-sh  One way you may be able to get around this is to use `shard.override.yml`, available in shards v0.12:

```
$ shards --version
Shards 0.12.0 [218eb62] (2020-08-12)

$ cat shard.override.yml
dependencies:
  db:
    github: jgaskins/crystal-db
    branch: generic-pool
```

and re-run `shards install`.

**Comment by Manu-sh** [comment]
@z64 thankyou for this information, maybe could be useful in future

**Comment by jgaskins** [comment]
@z64 TIL! This sounds like a _much_ cleaner stopgap than what I ended up doing. I forked `will/crystal-pg` to have it use my fork/branch of `crystal-db`. I just installed shards v0.12 and will definitely use this! Thank you!

**Comment by jgaskins** [comment]
@Manu-sh `crystal-db` v0.10 has been released with support for a generic connection pool. I've updated `shard.yml` with that version in [this commit](https://github.com/jgaskins/redis/commit/15b39ae6e9d4407d0118f2e5a5723784b0eef470) so we should be good to go here.
