### ISSUE TITLE
Support for `SCRIPT *`, `EVAL*`, `EVALSHA*`

### ISSUE THREAD

**Issue by robacarp** [jgaskins/redis#39]
[SCRIPT LOAD](https://redis.io/commands/script-load/) and other script commands allow an application developer to load custom Lua into Redis. [EVALSHA](https://redis.io/commands/evalsha/) allows execution of stored scripts in a similar manner to a stored procedure in a sql database.

Implementing any of the https://redis.io/docs/manual/patterns/distributed-locks according to the redis spec indicates that both are necessary.

**Comment by jgaskins** [comment]
Added in a7351c37afa7d12a396a8c7bcd573f148b5a75e0 just now. Let me know if it's what you need. I'll add documentation comments in another commit, but [the test](https://github.com/jgaskins/redis/blob/a7351c37afa7d12a396a8c7bcd573f148b5a75e0/spec/redis_spec.cr#L387-L430) has usage examples for both `eval` and `evalsha`. They were effectively identical so I added both. I also need to add `eval_ro` and `evalsha_ro` to [`Redis::Cluster::READ_ONLY_COMMANDS`](https://github.com/jgaskins/redis/blob/a7351c37afa7d12a396a8c7bcd573f148b5a75e0/src/cluster.cr#L214-L266).

**Comment by jgaskins** [comment]
Actually, going to reopen this because there are several other `SCRIPT` commands we should support:

- [ ] [SCRIPT DEBUG](https://redis.io/commands/script-debug/)
- [ ] [SCRIPT EXISTS](https://redis.io/commands/script-exists/)
- [ ] [SCRIPT FLUSH](https://redis.io/commands/script-flush/)
- [ ] [SCRIPT KILL](https://redis.io/commands/script-kill/)
- [x] [SCRIPT LOAD](https://redis.io/commands/script-load/)

**Comment by robacarp** [comment]
amazing! thank you!
