### ISSUE TITLE
ltrim broken?

### ISSUE THREAD

**Issue by robacarp** [jgaskins/redis#47]
```crystal
require "redis"

redis = ::Redis::Client.new(URI.parse("redis://localhost:1679"))

redis.lpush "test", ["23", "45"]
redis.ltrim "test", 0, 100
```

I also tried `redis.ltrim "test", "0", "100"` but it's the same.

I expected this code to work, but I could be missing something. This throws a compile time error of `Error: undefined method 'ltrim' for Redis::Client`. I see [ltrim in the `set_return_types!` macro](https://github.com/jgaskins/redis/blob/e1d8758544dd000e0319ab2ed9ec6d092fd8bd0f/src/connection.cr#L284) but I confess I really haven't taken the time to understand what's going on in there.

**Comment by jgaskins** [comment]
The `set_return_types!` macro is for convenience when running commands through `Client`, `Connection`, or `Cluster` to scope the return types down to just the types the Redis server will actually return instead of any type that can be parsed. This is needed because the same methods on `Pipeline` and `Transaction` aren't evaluated eagerly.

Regarding `ltrim`, it's possible I intended to add it and forgot. Some parts of this shard aren't as fleshed-out as I'd like. I keep meaning to sit down and add all the missing Redis commands (including some of the convenient overloads), but there are just soooo many of them. 😄

All that said, do you have any thoughts on the method signatures in #48?
